version: '3.8'
services:
    board-db:
        image: mysql:8.0
        container_name: board_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: board_db
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - board_db_data:/var/lib/mysql
    redis_container:
        image: redis:latest
        container_name: redis_test
        ports:
            - 6379:6379
        volumes:
            - ./redis/data:/data
            - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
        labels:
            - "name=redis"
            - "mode=standalone"
        restart: always
        command: redis-server /usr/local/conf/redis.conf		

volumes:
    board_db_data: